services:
  redis-fast-pix-worker:
    image: gacerioni/redis_fast_pix:0.0.3-workshop
    environment:
      REDIS_URL: "redis://gabs-pix-smasher-db-user:blabla@redis-12419.internal.c35402.us-east-1-mz.ec2.cloud.rlrcp.com:12419"
      REDIS_STREAM: "pix_payments"
      GROUP_NAME: "pix_consumers"
      IDLE_THRESHOLD_MS: "5000"
      BACKEND_RESPONSE_PREFIX: "backend_bacen_response_"
    deploy:
      replicas: 100  # Scale the number of workers as needed
    restart: always