# Use the official Python 3.12 slim image
FROM python:3.12-slim
LABEL authors="gabriel.cerioni@redis.com"

WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the main Python script into the container
COPY pix_smasher_demo.py .

# Set environment variables (if you need defaults for local testing)
ENV REDIS_URL=redis://localhost:6379
ENV REDIS_LIST=source_list

# Specify the default command to run the main script
CMD ["python3", "pix_smasher_demo.py"]