apiVersion: v1
kind: ConfigMap
metadata:
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  name: {{ include "redis-fast-pix.fullname" . }}-config
data:
  {{- if .Values.env }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}