apiVersion: v1
kind: Service
metadata:
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  name: {{ include "redis-fast-pix.fullname" . }}
  labels:
    {{- include "redis-fast-pix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "redis-fast-pix.selectorLabels" . | nindent 4 }}
